[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm install --omit=dev && npm run build:server"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"