[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm install && ./node_modules/.bin/tsc"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"