[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm ci --cache /tmp/.npm && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"